[package]
name = "counter"
version = "0.1.0"
edition = "2025"

[dependencies]
rmcp = { version = "0.8.1", features=["transport-io", "server"] }
serde_json = "1.0.139"
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
